[registries.crates-io]
protocol = "sparse"

[build]
rustc-wrapper = "sccache"
incremental = false
rustflags = ["--cfg=has_std", "-Cpanic=abort"]

[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

[profile.release]
opt-level = "z"
lto = "thin"
strip = true
codegen-units = 1
panic = "abort"

[profile.dev]
incremental = true

[profile.rust-analyzer]
inherits = "dev"
incremental = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Clink-arg=-fuse-ld=ld.mold",
    "-Zshare-generics=y",
    "-Csplit-debuginfo=unpacked",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-Clink-arg=-fuse-ld=ld64.lld",
    "-Zshare-generics=y",
    "-Csplit-debuginfo=unpacked",
]
