[registries.crates-io]
protocol = "sparse"

[build]
rustc-wrapper = "sccache"
incremental = false
rustflags = ["--cfg=has_std", "-Cpanic=abort"]

[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
panic = "abort"
